name: Unit Tests

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.14]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
          terraform_wrapper: false
      
      - name: Interact with Terraform
        run: terraform --version

      - name: Download Go Modules
        working-directory: test
        run: go mod download

      - name: Run Go Tests
        working-directory: test
        run: go test -v -tags=unit

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_bucket_name: ${{ secrets.FLUGEL_BUCKET_NAME }}
          
          TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}